apiVersion: v1
kind: Pod                                            # 1
metadata:
  name: sa-frontend3
  labels:
    app: sa-frontend                                 # 2
spec:                                                # 3
  containers:
    - image: cayamil/sentiment-analysis-frontend:v2 # 4
      name: sa-frontend                              # 5
      ports:
        - containerPort: 80                          # 6